/*
 * TMDQueue.h
 *
 *  Created on: May 4, 2023
 *      Author: Abdu
 */

#ifndef APP_HAL_PATTERNS_SERVER_TMDQUEUE_TMDQUEUE_H_
#define APP_HAL_PATTERNS_SERVER_TMDQUEUE_TMDQUEUE_H_





#endif /* APP_HAL_PATTERNS_SERVER_TMDQUEUE_TMDQUEUE_H_ */
