/*
 * TempratureSensor_HAL_Cfg.h
 *
 *  Created on: Mar 3, 2023
 *      Author: Abdu
 */

#ifndef TEMPRATURESENSOR_HAL_DYNAMIC_INC_TEMPRATURESENSOR_HAL_CFG_H_
#define TEMPRATURESENSOR_HAL_DYNAMIC_INC_TEMPRATURESENSOR_HAL_CFG_H_





#endif /* TEMPRATURESENSOR_HAL_DYNAMIC_INC_TEMPRATURESENSOR_HAL_CFG_H_ */
