/*
 * Normal_Queue_Cfg.h
 *
 *  Created on: Apr 14, 2023
 *      Author: Abdu
 */

#ifndef DATASTRUCTURE_NORMAL_QUEUE_DYNAMIC_INC_NORMAL_QUEUE_CFG_H_
#define DATASTRUCTURE_NORMAL_QUEUE_DYNAMIC_INC_NORMAL_QUEUE_CFG_H_


#define NORMAL_QUEUE_BUFFER_SIZE_STATIC     5


#endif /* DATASTRUCTURE_NORMAL_QUEUE_DYNAMIC_INC_NORMAL_QUEUE_CFG_H_ */
