/*
 * FireModelClient.h
 *
 *  Created on: Jul 7, 2023
 *      Author: Abdu
 */

#ifndef APP_HAL_PATTERN_FIREMODELCLIENT_FIREMODELCLIENT_H_
#define APP_HAL_PATTERN_FIREMODELCLIENT_FIREMODELCLIENT_H_



#endif /* APP_HAL_PATTERN_FIREMODELCLIENT_FIREMODELCLIENT_H_ */
